(deffacts sensors
	(sensor (number 1) (status good))
	(sensor (number 2) (status bad))
	(sensor (number 3) (status good))
	(sensor (number 4) (status good))
	(sensor (number 5) (status good))
	(sensor (number 6) (status good))
	(sensor (number 7) (status good))
	(sensor (number 8) (status bad))
	(sensor (number 9) (status bad))
	(sensor (number 10) (status good))
)